/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controler.Admin1Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author mahdi
 */
public class AddAirlines extends javax.swing.JFrame {
     Admin1Controller fa;
    /**
     * Creates new form AddAirlines
     */
    public AddAirlines() {
        initComponents();
        fa= new Admin1Controller();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//         airplaneIdTxt.setText("Enter text here...");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modelTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        firstClassSeatTxt = new javax.swing.JTextField();
        buisnessClassSeatstxt = new javax.swing.JTextField();
        RegNumberTxt = new javax.swing.JTextField();
        EconomyClasstxt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Class Seats");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 155, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buisness Class seats");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 161, 36));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Economy Class Seats");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 155, 32));
        jPanel1.add(modelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, 50));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 93, 36));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 738, 133, 24));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Registration Number");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 31));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Manufacturor ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 177, 36));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Model");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 155, 32));

        firstClassSeatTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstClassSeatTxtKeyTyped(evt);
            }
        });
        jPanel1.add(firstClassSeatTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 233, 50));

        buisnessClassSeatstxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buisnessClassSeatstxtKeyTyped(evt);
            }
        });
        jPanel1.add(buisnessClassSeatstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 101, 230, 50));
        jPanel1.add(RegNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 200, 50));

        EconomyClasstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EconomyClasstxtActionPerformed(evt);
            }
        });
        EconomyClasstxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EconomyClasstxtKeyTyped(evt);
            }
        });
        jPanel1.add(EconomyClasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 240, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Airbus", "Boeing", "Bombardier", "Embraer", "Lockheed Martin", "ATR (Aerei da Trasporto Regionale)", "Cessna (Textron Aviation)", "Gulfstream Aerospace", "Dassault Aviation", "Sukhoi Civil Aircraft Company" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 200, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\mahdi\\Downloads\\s3_field_feature_image_shutterstock_753807385.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 940, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              if (   
                   modelTxt.getText().isEmpty()
                || firstClassSeatTxt.getText().isEmpty()
                || buisnessClassSeatstxt.getText().isEmpty()
                || RegNumberTxt.getText().isEmpty() 
                || EconomyClasstxt.getText().isEmpty()) {
                   JOptionPane.showMessageDialog(null, "fill all the text");
                   return;
                 }
            try {
                String registrationNumber = RegNumberTxt.getText();
                String manufacturer = jComboBox1.getSelectedItem()+"";
                String model = modelTxt.getText();
                int FirstClassSeats = Integer.parseInt(firstClassSeatTxt.getText());
                int BuisnessClassSeats = Integer.parseInt(buisnessClassSeatstxt.getText());
                int EconomyClassSeats = Integer.parseInt(EconomyClasstxt.getText());
               
                if (fa.addAirplane(FirstClassSeats, BuisnessClassSeats, EconomyClassSeats, manufacturer, model, registrationNumber)) {
                    JOptionPane.showMessageDialog(null, "Succesfull");
                    modelTxt.setText("");      
                    firstClassSeatTxt.setText("");
                    buisnessClassSeatstxt.setText("");
                    RegNumberTxt.setText("");
                    EconomyClasstxt.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "fail");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Number");
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstClassSeatTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstClassSeatTxtKeyTyped
        char g = evt.getKeyChar();
        if (!Character.isDigit(g)) {
            evt.consume();
        }
    }//GEN-LAST:event_firstClassSeatTxtKeyTyped

    private void buisnessClassSeatstxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buisnessClassSeatstxtKeyTyped
        char g = evt.getKeyChar();
        if (!Character.isDigit(g)) {
            evt.consume();
        }
    }//GEN-LAST:event_buisnessClassSeatstxtKeyTyped

    private void EconomyClasstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EconomyClasstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EconomyClasstxtActionPerformed

    private void EconomyClasstxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EconomyClasstxtKeyTyped
        char g = evt.getKeyChar();
        if (!Character.isDigit(g)) {
            evt.consume();
        }
    }//GEN-LAST:event_EconomyClasstxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAirlines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAirlines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAirlines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAirlines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAirlines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EconomyClasstxt;
    private javax.swing.JTextField RegNumberTxt;
    private javax.swing.JTextField buisnessClassSeatstxt;
    private javax.swing.JTextField firstClassSeatTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField modelTxt;
    // End of variables declaration//GEN-END:variables
}
