/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import controler.Admin1Controller;
import java.time.LocalDate;

import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahdi
 */
public class UpdateFlight extends javax.swing.JFrame {

    Admin1Controller fa;
    DefaultTableModel model;

    public UpdateFlight() {
        initComponents();
        fa = new Admin1Controller();
        model = (DefaultTableModel) jTable6.getModel();
        String[][] Ar = fa.fillTableWithFlightInformation();
        fa.updateStatus();
        for (int i = 0; i < fa.getAllAirplaneID().size(); i++) {
            airplaneID.addItem(fa.getAllAirplaneID().get(i));
        }
        for (int i = 0; i < Ar[0].length; i++) {
               
                flightidcmb.addItem(Ar[5][i]);
                model.addRow(new Object[]{
                    Ar[0][i],
                    Ar[1][i],
                    Ar[2][i],
                    Ar[3][i],
                    Ar[4][i],
                    Ar[5][i],
                    Ar[6][i]});
            
        }

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        flightidcmb = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDateChooser7 = new com.toedter.calendar.JDateChooser();
        airplaneID = new javax.swing.JComboBox<>();
        DestinationDate = new javax.swing.JComboBox<>();
        DepartureDatecmb = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 0));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 6, 87, -1));

        jButton1.setText("cancel a fligth");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 140, 30));

        jButton2.setText("change time");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 127, 30));
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 270, 30));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Departure Airport", "Destination Airport", "Travel Date", "Travel Time", "Price", "Flight id", "AirplaneID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable6.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTable6VetoableChange(evt);
            }
        });
        jScrollPane6.setViewportView(jTable6);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 197, 860, 370));

        jPanel7.add(flightidcmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 30));

        jButton4.setText("Change Date");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 127, 30));

        jButton3.setText("Change price");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 140, 30));
        jPanel7.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 30));

        jButton5.setText("Change Destination");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 140, 30));

        jButton6.setText("Change Departure");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 130, 30));
        jPanel7.add(jDateChooser7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 270, 30));

        jPanel7.add(airplaneID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 30));

        DestinationDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rafic Hariri International Airport (Beirut, Lebanon)", "Hartsfield-Jackson Atlanta International Airport (United States)", "Heathrow Airport (United Kingdom)", "Dubai International Airport (United Arab Emirates)", "Beijing Capital International Airport (China)", "Los Angeles International Airport (United States)", "Tokyo Haneda Airport (Japan)", "O'Hare International Airport (Chicago, United States)", "Charles de Gaulle Airport (Paris, France)", "Frankfurt Airport (Germany)", "Amsterdam Airport Schiphol (Netherlands)", "Singapore Changi Airport (Singapore)", "King Abdulaziz International Airport (Jeddah, Saudi Arabia)", "Hamad International Airport (Doha, Qatar)", "King Khalid International Airport (Riyadh, Saudi Arabia)", "Istanbul Airport (Turkey)", "Suvarnabhumi Airport (Bangkok, Thailand)", "Sydney Airport (Australia)", "Indira Gandhi International Airport (New Delhi, India)", "Leonardo da Vinci–Fiumicino Airport (Rome, Italy)", "King Fahd International Airport (Dammam, Saudi Arabia)", "King Abdulaziz International Airport (Dammam, Saudi Arabia)", "Cairo International Airport (Egypt)", "Dubai International Airport (United Arab Emirates)", "Abu Dhabi International Airport (United Arab Emirates)" }));
        jPanel7.add(DestinationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, -1));

        DepartureDatecmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rafic Hariri International Airport (Beirut, Lebanon)", "Hartsfield-Jackson Atlanta International Airport (United States)", "Heathrow Airport (United Kingdom)", "Dubai International Airport (United Arab Emirates)", "Beijing Capital International Airport (China)", "Los Angeles International Airport (United States)", "Tokyo Haneda Airport (Japan)", "O'Hare International Airport (Chicago, United States)", "Charles de Gaulle Airport (Paris, France)", "Frankfurt Airport (Germany)", "Amsterdam Airport Schiphol (Netherlands)", "Singapore Changi Airport (Singapore)", "King Abdulaziz International Airport (Jeddah, Saudi Arabia)", "Hamad International Airport (Doha, Qatar)", "King Khalid International Airport (Riyadh, Saudi Arabia)", "Istanbul Airport (Turkey)", "Suvarnabhumi Airport (Bangkok, Thailand)", "Sydney Airport (Australia)", "Indira Gandhi International Airport (New Delhi, India)", "Leonardo da Vinci–Fiumicino Airport (Rome, Italy)", "King Fahd International Airport (Dammam, Saudi Arabia)", "King Abdulaziz International Airport (Dammam, Saudi Arabia)", "Cairo International Airport (Egypt)", "Dubai International Airport (United Arab Emirates)", "Abu Dhabi International Airport (United Arab Emirates)" }));
        jPanel7.add(DepartureDatecmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 122, 270, 30));

        jButton7.setText("Change Airplane");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mahdi\\Pictures\\frequent-flier-program-GettyImages-539327295.jpg")); // NOI18N
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 860, 570));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 865, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (flightidcmb.getSelectedObjects().length == 0) {
            JOptionPane.showMessageDialog(null, "No flight is added");
            return;
        }

        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to execute this action?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            String s = flightidcmb.getSelectedItem().toString();
            fa.deleteFlight(s);
            flightidcmb.removeItem(s);
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                if (model.getValueAt(i, 5) != null && model.getValueAt(i, 5).equals(s)) {
                    model.removeRow(i);
                }
            }
        } else {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (flightidcmb.getSelectedObjects().length == 0) {
            JOptionPane.showMessageDialog(null, "No flight is added");
            return;
        }

        String FlightID = flightidcmb.getSelectedItem().toString();
        String changeTime = jTextField1.getText();

        if (!changeTime.trim().isEmpty()) {
            fa.ChangeTime(FlightID, changeTime);
            jTextField1.setText("");
            for (int i = 0; i < jTable6.getRowCount(); i++) {
                if (model.getValueAt(i, 5) != null && model.getValueAt(i, 5).equals(FlightID)) {
                    model.setValueAt(changeTime, i, 3);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Change time is empty. No update performed.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (flightidcmb.getSelectedObjects().length == 0) {
            JOptionPane.showMessageDialog(null, "No flight is added");
            return;
        }

        try {
            String FlightID = flightidcmb.getSelectedItem().toString();
            java.util.Date utilDate = jDateChooser7.getDate();
            java.sql.Date DepartureDate = new java.sql.Date(utilDate.getTime());
            if (DepartureDate.toLocalDate().isBefore(LocalDate.now())) {
                JOptionPane.showMessageDialog(null, "Invalid Date ");
                return;
            }
            fa.ChangeDate(FlightID, DepartureDate);
            jDateChooser7.cleanup();
            for (int i = 0; i < jTable6.getRowCount(); i++) {
                if (model.getValueAt(i, 5) != null && model.getValueAt(i, 5).equals(FlightID)) {
                    model.setValueAt(DepartureDate, i, 2);
                }
            }

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, "Enter a date");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (flightidcmb.getSelectedObjects().length == 0) {
            JOptionPane.showMessageDialog(null, "No flight is added");
            return;
        }
        String FlightID = flightidcmb.getSelectedItem().toString();

        if (!jTextField2.getText().isEmpty()) {
            int price = Integer.parseInt(jTextField2.getText());
            fa.ChangeFlightPrice(FlightID, price);
            jTextField2.setText("");
            for (int i = 0; i < jTable6.getRowCount(); i++) {
                if (model.getValueAt(i, 5) != null && model.getValueAt(i, 5).equals(FlightID)) {
                    model.setValueAt(price+"$", i, 4);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter a Price");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (flightidcmb.getSelectedObjects().length == 0) {
            JOptionPane.showMessageDialog(null, "No flight is added");
            return;
        }
        String FlightID = flightidcmb.getSelectedItem().toString();
        String destination = DestinationDate.getSelectedItem().toString();

        if (!destination.isEmpty()) {
            for (int i = 0; i < jTable6.getRowCount(); i++) {
                if (model.getValueAt(i, 0).equals(destination)) {
                    JOptionPane.showMessageDialog(null, "Invalid Destination Airport");
                    return;
                }
                if (model.getValueAt(i, 5) != null && model.getValueAt(i, 5).equals(FlightID)) {
                    model.setValueAt(destination, i, 1);
                }
            }
            fa.ChangeFlightDestination(FlightID, destination);
        } else {
            JOptionPane.showMessageDialog(this, "No update performed.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (flightidcmb.getSelectedObjects().length == 0) {
            JOptionPane.showMessageDialog(null, "No flight is added");
            return;
        }
        String FlightID = flightidcmb.getSelectedItem().toString();
        String departure = DepartureDatecmb.getSelectedItem().toString();

        if (!departure.isEmpty()) {
//            fa.ChangeFlightDeparture(FlightID, departure);
            for (int i = 0; i < jTable6.getRowCount(); i++) {
                if (model.getValueAt(i, 5) != null && model.getValueAt(i, 5).equals(FlightID)) {
                    if (model.getValueAt(i, 1).equals(departure)) {
                        JOptionPane.showMessageDialog(null, "Invalid Departure Airport");
                        return;
                    }
                }
                if (model.getValueAt(i, 5) != null && model.getValueAt(i, 5).equals(FlightID)) {
                    model.setValueAt(departure, i, 0);
                }
            }
            fa.ChangeFlightDeparture(FlightID, departure);
        } else {
            JOptionPane.showMessageDialog(this, " No update performed.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable6VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTable6VetoableChange

    }//GEN-LAST:event_jTable6VetoableChange

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (flightidcmb.getSelectedObjects().length == 0) {
            JOptionPane.showMessageDialog(null, "No flight is added");
            return;
        }
        String FlightID = flightidcmb.getSelectedItem().toString();
        int airplaneid = Integer.parseInt(airplaneID.getSelectedItem().toString());
        if (airplaneid!=0) {
            fa.ChangeAirplane(FlightID, airplaneid);
            for (int i = 0; i < jTable6.getRowCount(); i++) {
                if (model.getValueAt(i, 5) != null && model.getValueAt(i, 5).equals(FlightID)) {
                    model.setValueAt(airplaneid, i, 6);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No update performed.");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DepartureDatecmb;
    private javax.swing.JComboBox<String> DestinationDate;
    private javax.swing.JComboBox<String> airplaneID;
    private javax.swing.JComboBox<String> flightidcmb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
